test:
  build: .
  links:
    - rabbitmq
  command: npm test
  environment:
    - AMQP_URL=amqp://guest:guest@rabbitmq//
    - DEBUG=${DEBUG}
  volumes:
    - ./test:/code/test
    - ./icqueue.js:/code/icqueue.js

rabbitmq:
  image: rabbitmq

